# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5785068b575ade3ab2cd36a6955ba75db3417bf3ac9da88a260fff6352789610f6cf35eee0b4a0a8ce80117ae51e51848fb7e3212f237f49eb7aba59e6fb4075

test:
  secret_key_base: f5b63e0bdfaf9294e52e5bb820d0d08a6517e063f8f27a27a44861f4fbb25158701c0012a1693af9282700f86bee6a45f766f8b2305b6558416fc4ae6037947e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
